name: CI – FastAPI

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ main, feature/examen ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Installer les dépendances
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov httpx

      # Exécuter les tests
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -v

      # Mesurer la couverture
      - name: Measure coverage
        run: pytest --cov=app --cov-report=term-missing
